dependencies:
  - role: timeseer_network
galaxy_info:
  author: Jeroen Hoekx, Diogo Lobo
  role_name: timeseer_data_service
  description: configure timeseer_data_service
  license: license (MIT)
  min_ansible_version: "2.5"
