dependencies:
  - role: timeseer_network
galaxy_info:
  author: Jeroen Hoekx, Diogo Lobo
  role_name: traefik
  description: configure traefik for timeseer
  license: license (MIT)
  min_ansible_version: "2.5"
